# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: chmod -R 777 /var/lib/gems/2.5.0
  displayName: 'Gem Permission'

- script: |
    gem install bundler
  displayName: 'bundle install'

- script: bundle exec rake
  displayName: 'bundle exec rake'
