# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:

- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: apt update && apt install ruby-full && ruby --version
  displayName: 'Ruby Install'

- script: gem install rails && rails -v
  displayName: 'Rails Install'

- script: gem install buldler && bundle install && rails s
  displayName: 'Server'

# - script: |
#     gem install bundler
#   displayName: 'bundle install'

# - script: bundle exec rake
#   displayName: 'bundle exec rake'
