# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:

- script: echo Hello, world! && ruby -v
  displayName: 'Run a one-line script'

- script: sudo apt-get install libsqlite3-dev && sudo gem install sqlite3 -v '1.4.2' --source 'https://rubygems.org/'
  displayName: 'Sqlite Install'

- script: sudo yarn install --check-files
  displayName: 'yarn packages update'
  

# - script: sudo apt update && sudo apt install ruby-full && ruby --version
#   displayName: 'Ruby Install'

# - script: sudo gem install rails && rails -v
#   displayName: 'Rails Install'

- script: sudo gem install bundler && sudo bundle install && rails s
  displayName: 'Server'

# - script: |
#     gem install bundler
#   displayName: 'bundle install'

# - script: bundle exec rake
#   displayName: 'bundle exec rake'
